name: job concurrency: 

on:
 push:
  branches: [main]

  jobs:
   build:
    run-on: ubuntu-latest

concurrency:
 group: deploy
 cancel-in-progress: true

 steps: 
  - name: checkout reopositroy 
  
    uses: actions/checkout@v6.0.2 
  
  - name: install dependencies
  
    run: npm install 
    
  - name: build next.js app
  
    run: npm run build

    -name: deploy app
    run: echo "deploy app"
     
    
   
